apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "keycloak-operator.fullname" . }}-controller-cluster-role
  labels:
  {{- include "keycloak-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - k8s.keycloak.org
  resources:
  - keycloaks
  - keycloaks/status
  - keycloaks/finalizers
  verbs:
  - get
  - list
  - watch
  - patch
  - update
  - create
  - delete