apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "keycloak-operator.fullname" . }}-operator
  labels:
  {{- include "keycloak-operator.labels" . | nindent 4 }}
  annotations:
    app.quarkus.io/build-timestamp: 2023-07-18 - 10:05:37 +0000
spec:
  replicas: {{ .Values.operator.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/version: 22.0.1
    {{- include "keycloak-operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/version: 22.0.1
      {{- include "keycloak-operator.selectorLabels" . | nindent 8 }}
      annotations:
        app.quarkus.io/build-timestamp: 2023-07-18 - 10:05:37 +0000
    spec:
      containers:
      - env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: OPERATOR_KEYCLOAK_IMAGE
          value: {{ quote .Values.operator.keycloakOperator.env.operatorKeycloakImage }}
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.operator.keycloakOperator.image.repository }}:{{ .Values.operator.keycloakOperator.image.tag
          | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.operator.keycloakOperator.imagePullPolicy }}
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /q/health/live
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 10
        name: keycloak-operator
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /q/health/ready
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 10
        resources: {}
        startupProbe:
          failureThreshold: 3
          httpGet:
            path: /q/health/started
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 10
      serviceAccountName: {{ include "keycloak-operator.fullname" . }}-operator