apiVersion: v1
kind: Service
metadata:
  name: {{ include "keycloak-operator.fullname" . }}-operator
  labels:
  {{- include "keycloak-operator.labels" . | nindent 4 }}
  annotations:
    app.quarkus.io/build-timestamp: 2023-07-18 - 10:05:37 +0000
spec:
  type: {{ .Values.operator.type }}
  selector:
    app.kubernetes.io/version: 22.0.1
  {{- include "keycloak-operator.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.operator.ports | toYaml | nindent 2 -}}