apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "keycloak-operator.fullname" . }}-realmimportcontroller-cluster-role
  labels:
  {{- include "keycloak-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - k8s.keycloak.org
  resources:
  - keycloakrealmimports
  - keycloakrealmimports/status
  - keycloakrealmimports/finalizers
  verbs:
  - get
  - list
  - watch
  - patch
  - update
  - create
  - delete