apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "keycloak-operator.fullname" . }}-operator
  labels:
  {{- include "keycloak-operator.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.operator.serviceAccount.annotations | nindent 4 }}