name: Release Charts

on:
  push:
    branches:
      - main

env:
  CHARTNAME: keycloak-operator

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0


      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.8.1

      - name: Add dependency chart repos
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.4.0
        with:
          charts_dir: chart
          config: cr.yaml
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: install cosign
        uses: sigstore/cosign-installer@main

      - name: Log into ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Build the helm chart and sign the oci image
        shell: bash
        run: |
          rm -rf dist
          mkdir dist
          echo ${{ secrets.REGISTRY_TOKEN }} | helm registry login ghcr.io --username ${{ github.repository_owner }} --password-stdin
          helm package ${{ env.CHARTNAME }} --destination dist
          helm push dist/${{ env.CHARTNAME }}-*.tgz oci://ghcr.io/fire-ant > .digest
          cat .digest | awk -F "[, ]+" '/Digest/{print $NF}'
          cosign sign ghcr.io/fire-ant/${{ env.CHARTNAME }}@$(cat .digest | awk -F "[, ]+" '/Digest/{print $NF}') --yes
